### ISSUE TITLE
Whitelist is not respected

### ISSUE THREAD

**Issue by MadsRC** [NateBrune/silk-guardian#13]
I've been trying to get this working today, but noticed that it doesn't seem to respect the whitelist.

lsusb outputs:

   Bus 001 Device 003: ID 046d:12ab Logitech, Inc. Unifying Receiver

Note: I've changed the USB ID from the original.

I thus enter, in `config.h`:

```
{ USB_DEVICE(0x046d, 0x12ab) },
{  },
```

However, when i remove said USB device from my machine, after compilation and insertion of the module, a reboot happens.

Please note that I've also commented out the remove_files part:

```
/*  "/home/user/privatekey",
    "/private/ssnumber.pdf", */
    NULL,   /* Must be NULL terminated */
};
```

I'm on Ubuntu 16.04, using 4.4.0-34-generic kernel

**Comment by NateBrune** [comment]
You are so right... 
I will look into it this weekend.
P.S. Sorry I didn't see this sooner, I must have just missed it.

**Comment by pepa65** [comment]
Any progress on fixing the whitelist?

**Comment by pepa65** [comment]
I think the test should be reversed; removing the exclamation mark in `while (!dev_id)`
