### ISSUE TITLE
The shred utility is useless to journaling file systems!

### ISSUE THREAD

**Issue by GreenJoey** [NateBrune/silk-guardian#21]
The shred utility is useless against Journaling file-systems like xfs. As per its man page

**Comment by amak79** [comment]
This is true with ext3/4 when the data ordering mode is `data=journal`, but not when `data=ordered` (the default) or `data=writeback` is used. There is probably nothing that can be done since `shred` cannot guarantee that the data has been overwritten when shredding single files.
