### ISSUE TITLE
kernel:NMI watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [thread1:6678]

### ISSUE THREAD

**Issue by Osndok** [NateBrune/silk-guardian#9]
Greetings,

I was curious to try this out, but it did not seem to work as expected.

In particular, a kernel mode process named ***thread1*** would wholly occupy one processing core until the module was removed. While in this state, random processes (which I suppose where pinned to that core) would also take a very long break from being useful. I would be happy to provide more details, but I'm more interested in why this might happen.

> Linux redacted-hostname 4.4.6-200.fc22.x86_64 #1 SMP Wed Mar 16 22:13:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Osndok** [comment]
I think the easiest way to fix this issue would be to just sleep for a fixed interval:
[silk-msleep.diff.txt](https://github.com/NateBrune/silk-guardian/files/190054/silk-msleep.diff.txt)

However, when also considering #10 (just now filed)... perhaps there simply a usbcore callback that you can register for when a bus reset occurs?

**Comment by NateBrune** [comment]
This should be fixed by implementing the driver as something other than a while loop. Namely, registering a callback. I tried it for a bit but it didn't seem to work. I will put in more work to try it again. If I get it working like it should, then this would not lockup a cpu and everything would go more smoothly, I will keep you up to date thank you.

**Comment by Osndok** [comment]
I would be interested in hacking at the broken callback code, if you could push that to a separate branch... :-)

**Comment by NateBrune** [comment]
https://github.com/NateBrune/silk-guardian/tree/f7db7e49d43f6c0174a50b72700bea56554d0ecc here you are... good luck! thank you for helping out. :)
